# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L84Tt6PY8V4JfgX7doKr-5xT7_hsuYs4
"""

import numpy as np
import pandas as pd

# give you file path here
dataset = pd.read_csv('/content/churn_data.csv')

dataset.head()

dataset.info()

print(dataset.isnull().sum())
print(dataset.describe())

dataset.info()

import seaborn as sns
import matplotlib.pyplot as plt

# Changed 'Churn' to 'churn'
print(dataset['churn'].value_counts())

# Changed x='Churn' to x='churn'
sns.countplot(x='churn', data=dataset, palette='coolwarm')

plt.title('Churn Distribution')
plt.xlabel('Churn (0 = No, 1 = Yes)')
plt.ylabel('Count')
plt.show()

# Fix missing values in your actual columns
dataset['credit_score'] = dataset['credit_score'].fillna(dataset['credit_score'].median())
dataset['rewards_earned'] = dataset['rewards_earned'].fillna(dataset['rewards_earned'].median())
dataset['age'] = dataset['age'].fillna(dataset['age'].median())

# Verify that the missing values are gone
print(dataset.isnull().sum())

dataset.info()

from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()

# Using the actual categorical columns present in your churn_data.csv
categorical_cols = ['housing', 'payment_type', 'zodiac_sign']

for col in categorical_cols:
    dataset[col] = labelencoder.fit_transform(dataset[col])

# Verify that the columns have been successfully encoded into numbers
dataset[categorical_cols].head()

from sklearn.model_selection import train_test_split

# Drop 'user' (the actual ID column) and 'churn' (the target column) to get features
X = dataset.drop(['user', 'churn'], axis=1)

# Set the target variable using the correct lowercase 'churn'
y = dataset['churn']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Verify the shapes of your splits
print(f"X_train shape: {X_train.shape}, X_test shape: {X_test.shape}")

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

